import { versions } from '../templates/versions.js';
import { getPackageVersion } from '../version.js';
import type { Workspace } from './project.js';
import type { ChangePlan } from './changes.js';
import {
  render,
  initialPlan,
  guardedRead,
  object,
  json,
  retainNewlines,
  metadata,
} from './planning.js';

/** Read-only comparison against the official generator's latest stable release. */
export interface UpgradeCheck {
  cliVersion: string;
  projectGenerator: string;
  latestStable: string;
  updateAvailable: boolean;
  projectBehind: boolean;
  /** Versions tested together by the running CLI, not by the remote release. */
  baseline: typeof versions;
  registry: string;
}

function stableVersion(value: unknown): bigint[] {
  if (
    typeof value !== 'string' ||
    !/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/.test(
      value,
    )
  ) {
    throw new Error(
      'Expected a stable semantic version in generator release metadata.',
    );
  }
  return value
    .split('+')[0]!
    .split('.')
    .map((part) => BigInt(part));
}

function isNewer(latest: string, current: string): boolean {
  const target = stableVersion(latest);
  // A stable version supersedes a prerelease with the same core version.
  const match =
    /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/.exec(
      current,
    );
  if (!match)
    throw new Error(
      'The project or CLI generator version is not a semantic version.',
    );
  if (
    match[4]
      ?.slice(1)
      .split('.')
      .some(
        (part) => /^\d+$/.test(part) && part.length > 1 && part.startsWith('0'),
      )
  ) {
    throw new Error(
      'The project or CLI generator version is not a semantic version.',
    );
  }
  for (let index = 0; index < 3; index++) {
    const installed = BigInt(match[index + 1]!);
    if (target[index]! !== installed) return target[index]! > installed;
  }
  return Boolean(match[4]);
}

const exactVersion =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;

/** Extend the release comparison to exact dependency prereleases. */
function newerExact(latest: string, current: string): boolean {
  const target = exactVersion.exec(latest);
  const installed = exactVersion.exec(current);
  if (!target || !installed)
    throw new Error('Expected an exact semantic version.');
  if (!target[4]) return isNewer(latest, current);
  const targetCore = target.slice(1, 4).join('.');
  const installedCore = installed.slice(1, 4).join('.');
  if (targetCore !== installedCore) return isNewer(targetCore, installedCore);
  if (!installed[4]) return false;
  const a = target[4].split('.');
  const b = installed[4].split('.');
  for (let index = 0; index < Math.max(a.length, b.length); index++) {
    const left = a[index];
    const right = b[index];
    if (left === right) continue;
    if (left === undefined) return false;
    if (right === undefined) return true;
    const numericLeft = /^\d+$/.test(left);
    const numericRight = /^\d+$/.test(right);
    if (numericLeft && numericRight) return BigInt(left) > BigInt(right);
    if (numericLeft !== numericRight) return numericRight;
    return left > right;
  }
  return false;
}

export async function planUpgrade(workspace: Workspace): Promise<ChangePlan> {
  const cliVersion = await getPackageVersion();
  if (newerExact(workspace.config.generator, cliVersion))
    throw new Error(
      `This workspace was generated by a newer CLI (${workspace.config.generator}). Upgrade the CLI first.`,
    );
  if (workspace.config.packageManager !== 'pnpm')
    throw new Error('Only pnpm workspaces can be upgraded.');

  const plan = initialPlan(workspace);
  const generated = await render(
    workspace,
    workspace.config.apps,
    workspace.config.example,
    workspace.config.auth,
  );
  for (const app of workspace.config.apps) {
    if (app.example === undefined || app.example === workspace.config.example)
      continue;
    const files = await render(
      workspace,
      [app],
      app.example,
      workspace.config.auth,
    );
    const path = `apps/${app.name}/package.json`;
    generated.set(path, files.get(path)!);
  }
  const paths = [
    'package.json',
    ...workspace.config.apps.map((app) => `apps/${app.name}/package.json`),
    'packages/backend/package.json',
    'packages/typescript-config/package.json',
    'packages/eslint-config/package.json',
  ];
  const conflicts: string[] = [];
  for (const path of paths) {
    const before = await guardedRead(workspace, plan, path);
    if (before === null) throw new Error(`Missing manifest: ${path}.`);
    let parsed: unknown;
    try {
      parsed = JSON.parse(before);
    } catch {
      throw new Error(`Invalid JSON in ${path}.`);
    }
    const current = object(parsed, path);
    const baseline = object(JSON.parse(generated.get(path)!), path);
    let changed = false;
    const groups = [
      'dependencies',
      'devDependencies',
      'peerDependencies',
      'optionalDependencies',
    ];
    const managed = new Map<string, string>();
    for (const group of groups) {
      const tested = object(baseline[group], path);
      for (const [name, target] of Object.entries(tested)) {
        if (typeof target === 'string' && exactVersion.test(target))
          managed.set(name, target);
      }
    }
    const missing = new Set(managed.keys());
    for (const group of groups) {
      const existing = object(current[group], path);
      for (const [name, value] of Object.entries(existing)) {
        const target = managed.get(name);
        if (target === undefined) continue;
        missing.delete(name);
        if (value === target) continue;
        if (typeof value !== 'string' || !exactVersion.test(value)) {
          conflicts.push(
            `${path}: ${group}.${name} = ${typeof value === 'string' ? value : JSON.stringify(value)}`,
          );
        } else if (newerExact(value, target)) {
          plan.notes.push(
            `Kept ${name}@${value} in ${path}; it is newer than the tested ${target}.`,
          );
        } else if (newerExact(target, value)) {
          existing[name] = target;
          changed = true;
        }
      }
    }
    if (missing.size)
      plan.notes.push(
        `${path} is missing tested dependencies: ${[...missing].join(', ')}. Add them manually if needed.`,
      );
    if (path === 'package.json') {
      const manager = current.packageManager;
      if (manager === undefined) {
        plan.notes.push(
          'package.json is missing packageManager. Add it manually if needed.',
        );
      } else if (
        typeof manager !== 'string' ||
        !manager.startsWith('pnpm@') ||
        !exactVersion.test(manager.slice(5))
      ) {
        conflicts.push(
          `${path}: packageManager = ${typeof manager === 'string' ? manager : JSON.stringify(manager)}`,
        );
      } else if (newerExact(manager.slice(5), versions.pnpm)) {
        plan.notes.push(
          `Kept ${manager} in ${path}; it is newer than the tested ${versions.pnpm}.`,
        );
      } else if (newerExact(versions.pnpm, manager.slice(5))) {
        current.packageManager = `pnpm@${versions.pnpm}`;
        changed = true;
      }
    }
    if (changed) {
      const after = retainNewlines(json(current), before);
      if (after !== before) plan.changes.push({ path, before, after });
    }
  }
  if (conflicts.length)
    throw new Error(
      `Conflicting dependency pins:\n${conflicts.join('\n')}\nPin these to exact versions or remove the customization, then run upgrade again. No files were changed.`,
    );
  if (plan.changes.length || workspace.config.generator !== cliVersion) {
    await metadata(workspace, plan, { generator: cliVersion });
    const change = plan.changes.at(-1)!;
    change.after = retainNewlines(change.after, change.before);
    if (change.after === change.before) plan.changes.pop();
  }
  if (plan.changes.length)
    plan.notes.push(
      'Run pnpm install to update the lockfile, then run doctor.',
    );
  plan.notes.push(
    'Template files are not migrated; review the release notes for manual changes.',
  );
  return plan;
}

export async function checkUpgrade(
  workspace: Workspace,
  options: { signal?: AbortSignal; fetch?: typeof globalThis.fetch } = {},
): Promise<UpgradeCheck> {
  options.signal?.throwIfAborted();
  const cliVersion = await getPackageVersion();
  options.signal?.throwIfAborted();
  const registry = 'https://registry.npmjs.org/create-convex-monorepo/latest';
  const controller = new AbortController();
  const signal = options.signal
    ? AbortSignal.any([options.signal, controller.signal])
    : controller.signal;
  let timer: ReturnType<typeof setTimeout> | undefined;
  let abortListener: (() => void) | undefined;
  try {
    const cancelled = new Promise<never>((_, reject) => {
      abortListener = () =>
        reject(
          new Error(
            options.signal?.aborted
              ? 'Upgrade check cancelled.'
              : 'The npm registry check timed out after 10 seconds.',
          ),
        );
      signal.addEventListener('abort', abortListener, { once: true });
      timer = setTimeout(() => controller.abort(), 10_000);
    });
    const request = (async () => {
      const response = await (options.fetch ?? globalThis.fetch)(registry, {
        signal,
        headers: { accept: 'application/json' },
        redirect: 'error',
      });
      if (!response.ok)
        throw new Error(`The npm registry returned HTTP ${response.status}.`);
      const data: unknown = await response.json();
      if (typeof data !== 'object' || data === null || !('version' in data)) {
        throw new Error(
          'The npm registry returned invalid generator release metadata.',
        );
      }
      stableVersion(data.version);
      if (typeof data.version !== 'string')
        throw new Error('Invalid registry version.');
      return data.version;
    })();
    const latestStable = await Promise.race([request, cancelled]);
    return {
      cliVersion,
      projectGenerator: workspace.config.generator,
      latestStable,
      updateAvailable: isNewer(latestStable, cliVersion),
      projectBehind: isNewer(latestStable, workspace.config.generator),
      baseline: { ...versions },
      registry,
    };
  } finally {
    clearTimeout(timer);
    if (abortListener) signal.removeEventListener('abort', abortListener);
    controller.abort();
  }
}
