import { mkdir, readFile, writeFile, lstat } from 'node:fs/promises';
import { dirname, isAbsolute, relative, resolve, sep } from 'node:path';
import { formatGeneratedFile } from './format.js';
import type {
  GeneratorContext,
  PackageManifest,
  ProjectOptions,
} from './types.js';

export function mergeManifests(
  base: PackageManifest,
  patch: Partial<PackageManifest>,
): PackageManifest {
  const result = { ...base, ...patch };
  for (const field of [
    'scripts',
    'dependencies',
    'devDependencies',
    'peerDependencies',
    'optionalDependencies',
  ] as const) {
    const previous = base[field] as Record<string, string> | undefined;
    const next = patch[field] as Record<string, string> | undefined;
    if (!previous && !next) continue;
    for (const [name, value] of Object.entries(next ?? {})) {
      if (
        field !== 'scripts' &&
        previous?.[name] !== undefined &&
        previous[name] !== value
      )
        throw new Error(
          `Conflicting ${field} entry for ${name}: ${previous[name]} versus ${value}.`,
        );
    }
    result[field] = { ...previous, ...next };
  }
  for (const [name, version] of Object.entries(result.dependencies ?? {})) {
    if (
      result.devDependencies?.[name] !== undefined &&
      result.devDependencies[name] !== version
    )
      throw new Error(`Conflicting dependency versions for ${name}.`);
  }
  return result;
}

export function createContext(
  root: string,
  options: ProjectOptions,
): GeneratorContext {
  const owned = new Set<string>();
  async function safePath(path: string): Promise<string> {
    if (
      !path ||
      isAbsolute(path) ||
      path.includes('\\') ||
      path.split('/').includes('..')
    )
      throw new Error(`Unsafe output path: ${path}`);
    const target = resolve(root, path);
    const rel = relative(root, target);
    if (!rel || rel.startsWith(`..${sep}`) || isAbsolute(rel))
      throw new Error(`Unsafe output path: ${path}`);
    let current = root;
    for (const part of rel.split(sep)) {
      current = resolve(current, part);
      try {
        if ((await lstat(current)).isSymbolicLink())
          throw new Error(`Refusing symlink in output path: ${path}`);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
      }
    }
    return target;
  }
  return {
    options,
    root,
    scope: options.name,
    async write(path, contents) {
      const target = await safePath(path);
      if (owned.has(target))
        throw new Error(`Template output collision: ${path}`);
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, await formatGeneratedFile(path, contents), {
        flag: 'wx',
      });
      owned.add(target);
    },
    async json(path, value) {
      await this.write(path, `${JSON.stringify(value, null, 2)}\n`);
    },
    async mergePackage(path, patch) {
      const target = await safePath(path);
      if (!owned.has(target))
        throw new Error(
          `Cannot patch a package not generated by this context: ${path}`,
        );
      const base: PackageManifest = JSON.parse(await readFile(target, 'utf8'));
      await writeFile(
        target,
        await formatGeneratedFile(
          path,
          `${JSON.stringify(mergeManifests(base, patch), null, 2)}\n`,
        ),
      );
    },
  };
}
